### ISSUE TITLE
Button to deploy to Azure

### ISSUE THREAD

**Issue by Tapanila** [tomkerkhove/application-insights-connector#9]
Deploying the project into API apps should be as simple as possible.
There should be [Deploy to Azure button](https://deploy.azure.com) that would deploy this project.

**Comment by tomkerkhove** [comment]
Good suggestion @Tapanila, I'll look into it!

**Comment by tomkerkhove** [comment]
Reference on how to implement:

- https://deploy.azure.com
- [Using custom ARM templates with the Deploy to Azure button](https://elliotthamai.wordpress.com/2014/11/15/using-custom-arm-templates-with-the-deploy-to-azure-button/)
- [Git Repo](https://github.com/Tuesdaysgreen/HelloWorldMVCAppSettingDemo)

**Comment by tomkerkhove** [comment]
Deploy to Azure button is now available.
